#pragma once

#include "graph_definitions.dl"
#include "points_to.dl"
#include "utilities.dl"
#include "ir_type.dl"
#include "points_to.dl"

.decl sourceToSink(source: symbol, sourceId: number, sinkFunction: symbol, sinkIdx: symbol, sinkId: number)
.decl source(sourceFunction: symbol, retValueId: number)
.decl infectedBySource(sourceFunction: symbol, valueId: number)
.decl sink(sinkFunction: symbol, paramIdx: symbol, paramId: number)
.decl sourceName(name: symbol)
.input sourceName(filename="source_names.txt")
.decl sinkName(name: symbol)
.input sinkName(filename="sink_names.txt")

source(functionName, retId) :-
    sourceName(functionName),
    function_return(functionName, ret),
    edge(ret, retId, _, "value").

sink(functionName, idx, id) :-
    sinkName(functionName),
    vertex(functionId, _, _, functionName),
    edge(_, functionId, _, "callee"),
    edge(functionId, id, _, idx),
    IS_INTEGER(idx).

infectedBySource(sourceFunction, id) :-
    source(sourceFunction, id).

infectedBySource(sourceFunction, id) :-
    may_refer_to(id, infectedId),
    infectedBySource(sourceFunction, infectedId).

infectedBySource(sourceFunction, id) :-
    vertex(id, kind, _, _), 
    match(".*Operation", kind),
    edge(id, arg, _, _),
    infectedBySource(sourceFunction, arg).

sourceToSink(sourceName, sourceId, sinkFunction, sinkIdx, sinkId) :- 
    source(sourceName, sourceId),
    sink(sinkFunction, sinkIdx, sinkId),
    may_refer_to(sinkId, sourceId).

sourceToSink(sourceName, sourceId, sinkFunction, sinkIdx, sinkId) :- 
    infectedBySource(sourceName, infectedId),
    source(sourceName, sourceId),
    sink(sinkFunction, sinkIdx, sinkId),
    may_refer_to(sinkId, infectedId).

.output sourceToSink