#pragma once

#include "graph_definitions.dl"
#include "points_to.dl"
#include "utilities.dl"
#include "ir_type.dl"
#include "points_to.dl"

.decl sourceToSink(source: symbol, sourceId: number, sinkFunction: symbol, sinkIdx: symbol, sinkId: number)
.decl source(sourceFunction: symbol, retValueId: number)
.decl infectedBySource(sourceFunction: symbol, valueId: number)
.decl sink(sinkFunction: symbol, paramIdx: symbol, paramId: number)
.decl sourceName(name: symbol)
.input sourceName(filename="source_names.txt")
.decl sinkFunctionName(name: symbol)
.input sinkFunctionName(filename="sink_names.txt")

source(functionName, retId) :-
    sourceName(functionName),
    function_return(functionName, ret),
    edge(ret, retId, _, "value").

sink(functionName, idx, sinkId) :-
    sinkFunctionName(functionName),
    vertex(functionCallId, "Call", "Compound", "Call"),
    vertex(functionId, "Symbol", "Data", functionName),
    edge(functionCallId, functionId, "Data", "callee"),
    edge(functionCallId, sinkId, "Data", idx).

infectedBySource(sourceFunction, id) :-
    source(sourceFunction, id).

infectedBySource(sourceFunction, id) :-
    may_refer_to(id, infectedId),
    infectedBySource(sourceFunction, infectedId).

infectedBySource(sourceFunction, id) :-
    vertex(id, kind, _, _), 
    match(".*Operation", kind),
    edge(id, arg, _, _),
    infectedBySource(sourceFunction, arg).

infectedBySource(sourceFunction, objectId) :-
    vertex(objectId, "Allocation", _, _),
    edge(storeId, objectId, _, "object"),
    edge(storeId, valueId, _, "value"),
    infectedBySource(sourceFunction, valueId).

infectedBySource(sourceFunction, id) :-
    vertex(loadId, "Load", _, _),
    edge(loadId, objectId, _, "object"),
    ((id = loadId, infectedBySource(sourceFunction, objectId));
        (id = objectId, infectedBySource(sourceFunction, loadId))).

infectedBySource(sourceFunction, arrayId) :-
    vertex(arrayId, "Allocation", _, _),
    edge(arrayId, calleeId, _, "callee"),
    vertex(calleeId, "Symbol", "Data", "Array"),
    edge(arrayId, valueId, "Data", _),
    infectedBySource(sourceFunction, valueId).

infectedBySource(sourceFunction, objectId) :-
    vertex(loadId, "Load", _, _),
    edge(loadId, objectId, _, "object"),
    edge(callerId, loadId, _, "callee"),
    edge(callerId, valueId, "Data", _),
    infectedBySource(sourceFunction, valueId).

infectedBySource(sourceFunction, callerId) :-
    vertex(loadId, "Load", _, _),
    edge(loadId, objectId, _, "object"),
    edge(callerId, loadId, _, "callee"),
    infectedBySource(sourceFunction, objectId).

sourceToSink(sourceName, sourceId, sinkFunction, sinkIdx, sinkId) :- 
    source(sourceName, sourceId),
    sink(sinkFunction, sinkIdx, sinkId),
    may_refer_to(sinkId, sourceId).

sourceToSink(sourceName, sourceId, sinkFunction, sinkIdx, sinkId) :- 
    infectedBySource(sourceName, infectedId),
    source(sourceName, sourceId),
    sink(sinkFunction, sinkIdx, sinkId),
    may_refer_to(sinkId, infectedId).

.output sourceToSink