
#pragma once

.type irTypeSet = [ hd: irType, tl: irTypeSet ]
.type irTypeList = [ hd: irType, tl: irTypeList ]

.type irType =
      Any {}
    | Array { element_type: irType }
    | Boolean {}
    | Bottom {}
    | Function {  return_type: irType, parameters: irTypeList }
    | Integer {}
    | Null {}
    | Number {}
    | Object { value_type: irType }
    | String {}
    | Tuple { element_types: irTypeList }
    | Undefined {}
    | Union { types: irTypeSet }
    | UnsignedInt {}
    | UserDefined { name: symbol }
    | Void {}

.functor irTypeToString(t: irType): symbol stateful

.functor irTypeLub(t1: irType, t2: irType): irType stateful
.functor irTypeGlb(t1: irType, t2: irType): irType stateful

.lattice irType<> {
    Bottom -> $Bottom(),
    Lub -> @irTypeLub(_,_),
    Glb -> @irTypeGlb(_,_),
    Top -> $Any()
}

.functor getElementType(t: irType): irType stateful
.functor getFunctionRetType(t: irType): irType stateful
.functor getFunctionParamType(t: irType, index: number): irType stateful

.functor functionRetTemplate(ret: irType): irType stateful
.functor functionParamTemplate(param: irType, index: number): irType stateful
